server:
  port: ${SERVER_PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER_URL:localhost:9092}

consumer:
  topic: ${TOPIC:company-exemptions-delta}
  group_id: ${GROUP_ID:company-exemptions-delta-consumer}
  max_attempts: ${MAX_ATTEMPTS:5}
  backoff_delay: ${BACKOFF_DELAY:1000}
  concurrency: ${CONCURRENT_LISTENER_INSTANCES:1}


invalid_message_topic: ${INVALID_MESSAGE_TOPIC:company-exemptions-delta-company-exemptions-delta-consumer-invalid}

logger:
  namespace: company-exemptions-delta-consumer

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-exemptions-delta-consumer
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}
api:
  api-url: ${API_URL:localhost}
  api-key: ${CHS_API_KEY:chsApiKey}
  payments-url: ${PAYMENTS_URL:localhost}
