server:
  port: ${SERVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER_URL}

consumer:
  topic: ${TOPIC}
  group_id: ${GROUP_ID}
  max_attempts: ${MAX_ATTEMPTS}
  backoff_delay: ${BACKOFF_DELAY}
  concurrency: ${CONCURRENT_LISTENER_INSTANCES}


invalid_message_topic: ${INVALID_MESSAGE_TOPIC}

logger:
  namespace: company-exemptions-delta-consumer

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-exemptions-delta-consumer
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}
api:
  api-url: ${API_URL:localhost}
  api-key: ${CHS_API_KEY:chsApiKey}
  payments-url: ${PAYMENTS_URL:localhost}
